version: '3'

networks:
  sc-auth-net:
    driver: bridge

volumes:
  sc-auth-mongo:
    driver: local
  sc-auth-stan:
    driver: local

services:
  mongo:
    image: mongo:4.4.6
    ports:
      - 27001:27017
    networks:
      - sc-auth-net
    volumes:
      - sc-auth-mongo:/data/db
    restart: unless-stopped
  stan:
    image: nats-streaming:0.22.0-alpine
    command: [
      '-st', 'FILE',
      '--dir', '/data/nats',
      '-m', '8222',
      '-p', '4222',
      '-hbi', '5s',
      '-hbt', '5s',
      '-hbf', '2',
      '-SD',
      '-cid', 'sc-tech-test'
    ]
    ports:
      - 4221:4222
      - 8221:8222
    networks:
      - sc-auth-net
    volumes:
      - sc-auth-stan:/data/nats
    restart: unless-stopped
