version: '3'

networks:
  sc-test-net:
    driver: bridge

volumes:
  sc-test-mongo:
    driver: local
  sc-test-stan:
    driver: local

services:
  mongo:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    networks:
      - sc-test-net
    volumes:
      - sc-test-mongo:/data/db
    restart: unless-stopped
  stan:
    image: nats-streaming:0.22.0-alpine
    command: [
      '-st', 'FILE',
      '--dir', '/data/nats',
      '-m', '8222',
      '-p', '4222',
      '-hbi', '5s',
      '-hbt', '5s',
      '-hbf', '2',
      '-SD',
      '-cid', 'sc-tech-test'
    ]
    ports:
      - 4222:4222
      - 8222:8222
    networks:
      - sc-test-net
    volumes:
      - sc-test-stan:/data/nats
    restart: unless-stopped
  stan-console:
    image: mozgoo/nats-streaming-console
    depends_on:
      - stan
    ports:
      - 8282:8282
    networks:
      - sc-test-net
    environment:
      - 'STAN_URL=http://stan:4222'
      - 'STAN_MONITOR_URL=http://stan:8222'
      - 'STAN_CLUSTER=sc-tech-test'
    restart: unless-stopped
