apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: pramindanata/sc-user
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: 'production'
            - name: APP_PORT
              value: '4000'
            - name: APP_HOST
              value: 'http://localhost'
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APP_SECRET
            - name: DB_HOST
              value: 'mongodb://user-mongo-cluster-ip'
            - name: STAN_CLUSTER_ID
              value: 'sc-tech-test'
            - name: STAN_CLIENT_ID
              value: 'user-service'
            - name: STAN_URL
              value: 'http://stan-cluster-ip:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: user-service
      protocol: TCP
      port: 4000
      targetPort: 4000